-- MySQL Script generated by MySQL Workbench
-- Fri Nov 20 20:08:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb3` DEFAULT CHARACTER SET utf8 ;
USE `mydb3` ;

-- -----------------------------------------------------
-- Table `mydb3`.`Alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb3`.`Alumnos` ;

CREATE TABLE IF NOT EXISTS `mydb3`.`Alumnos` (
  `idAlumnos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `DNI` INT(8) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` BIGINT(10)  NOT NULL,
  `Localidad` VARCHAR(45) NOT NULL,
  `Foto` VARCHAR (100) NOT NULL, -- [Almacena solamente la Direccion de la Imagen]
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAlumnos`))
ENGINE = MyISAM
AUTO_INCREMENT = 1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
